version: '3'
services:
  client:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    environment:
      - PORT=9000
      - MONGO_URI=mongodb://mongo:27017/admin
    links:
      - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
